/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 5;
  /** RegularExpression Id. */
  int STRING = 6;
  /** RegularExpression Id. */
  int Num = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int TIMES = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int PRINTLN = 12;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int NEW = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int END = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int DIV = 20;
  /** RegularExpression Id. */
  int LPAR = 21;
  /** RegularExpression Id. */
  int RPAR = 22;
  /** RegularExpression Id. */
  int L_CB = 23;
  /** RegularExpression Id. */
  int R_cb = 24;
  /** RegularExpression Id. */
  int OP_ATRIB = 25;
  /** RegularExpression Id. */
  int OP_EQUAL = 26;
  /** RegularExpression Id. */
  int OP_NEQUAL = 27;
  /** RegularExpression Id. */
  int LTE = 28;
  /** RegularExpression Id. */
  int GTE = 29;
  /** RegularExpression Id. */
  int EQUAL = 30;
  /** RegularExpression Id. */
  int FIM = 31;
  /** RegularExpression Id. */
  int SCOLIN = 32;
  /** RegularExpression Id. */
  int LT = 33;
  /** RegularExpression Id. */
  int GT = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int TRUE = 37;
  /** RegularExpression Id. */
  int FALSE = 38;
  /** RegularExpression Id. */
  int NOT = 39;
  /** RegularExpression Id. */
  int Id = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"let\"",
    "<STRING>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"while\"",
    "\"println\"",
    "\"print\"",
    "\"new\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"end\"",
    "\"do\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\":=\"",
    "\"==\"",
    "\"~=\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\";;\"",
    "\";\"",
    "\"<\"",
    "\">\"",
    "\"&&\"",
    "\"||\"",
    "\"true\"",
    "\"false\"",
    "\"~\"",
    "<Id>",
  };

}
